import type { Question, PetResult, ShinyPet } from './types';

export const dimensionMeta: Record<string, { name: string; left: string; right: string }> = {
  E: { name: 'E 能量模式', left: '内敛蓄能', right: '外放燃烧' },
  S: { name: 'S 社交模式', left: '独行侠客', right: '社交悍匪' },
  B: { name: 'B 战斗风格', left: '谋定后动', right: '正面硬刚' },
  M: { name: 'M 情绪模式', left: '心如止水', right: '随性如风' },
  W: { name: 'W 世界观', left: '现世安稳', right: '星辰大海' },
};

export const dimensionOrder = ['E', 'S', 'B', 'M', 'W'];

/* ═══════════════════════════════════════════════
   34 PETS — base pool (the original 20 have shiny variants below;
   the additional 14 are classic pets without shiny rolls).
   Every single expect vector is UNIQUE.
   ═══════════════════════════════════════════════ */

const defaultCompats: Record<string, { name: string; type: string }[]> = {
  利灯鱼: [{"name": "雪影娃娃", "type": "默契型"}, {"name": "窃光蚊", "type": "幽影型"}, {"name": "夜枭", "type": "夜行型"}],
  夜枭: [{"name": "利灯鱼", "type": "孤灯型"}, {"name": "雪影娃娃", "type": "霜华型"}, {"name": "窃光蚊", "type": "隐秘型"}],
  恶魔狼: [{"name": "獠牙猪", "type": "冲锋型"}, {"name": "燃薪虫", "type": "火焰型"}, {"name": "酷拉", "type": "闪电型"}],
  燃薪虫: [{"name": "恶魔狼", "type": "暗牙型"}, {"name": "酷拉", "type": "雷动型"}, {"name": "雅丹鬃", "type": "风鬃型"}],
  疾光千兽: [{"name": "酷拉", "type": "闪电型"}, {"name": "雅丹鬃", "type": "风鬃型"}, {"name": "燃薪虫", "type": "烬燃型"}],
  窃光蚊: [{"name": "利灯鱼", "type": "孤灯型"}, {"name": "夜枭", "type": "夜行型"}, {"name": "雪影娃娃", "type": "霜华型"}],
  立方人: [{"name": "贝古斯", "type": "古械型"}, {"name": "雪影娃娃", "type": "理性型"}, {"name": "绒仙子", "type": "绒暖型"}],
  粉耳星兔: [{"name": "绒仙子", "type": "温柔型"}, {"name": "落陨星兔", "type": "陨星型"}, {"name": "小皮球", "type": "弹弹型"}],
  红绒十字: [{"name": "绒仙子", "type": "守护型"}, {"name": "落陨星兔", "type": "光芒型"}, {"name": "格兰球", "type": "圆滑型"}],
  绒仙子: [{"name": "粉耳星兔", "type": "萌星型"}, {"name": "奇丽花", "type": "花语型"}, {"name": "红绒十字", "type": "圣十字型"}],
  酷拉: [{"name": "燃薪虫", "type": "火焰型"}, {"name": "疾光千兽", "type": "极光型"}, {"name": "恶魔狼", "type": "暗牙型"}],
  雪影娃娃: [{"name": "利灯鱼", "type": "孤灯型"}, {"name": "窃光蚊", "type": "窃影型"}, {"name": "夜枭", "type": "夜行型"}],
  奇丽花: [{"name": "绒仙子", "type": "绒暖型"}, {"name": "雪影娃娃", "type": "霜华型"}, {"name": "红绒十字", "type": "守护型"}],
  小皮球: [{"name": "粉耳星兔", "type": "萌星型"}, {"name": "格兰球", "type": "滚动型"}, {"name": "落陨星兔", "type": "陨星型"}],
  月牙雪熊: [{"name": "雪影娃娃", "type": "霜华型"}, {"name": "贝古斯", "type": "古械型"}, {"name": "利灯鱼", "type": "孤灯型"}],
  格兰球: [{"name": "小皮球", "type": "弹弹型"}, {"name": "红绒十字", "type": "圣十字型"}, {"name": "绒仙子", "type": "绒暖型"}],
  獠牙猪: [{"name": "恶魔狼", "type": "暗牙型"}, {"name": "燃薪虫", "type": "烬燃型"}, {"name": "酷拉", "type": "雷动型"}],
  落陨星兔: [{"name": "粉耳星兔", "type": "萌星型"}, {"name": "红绒十字", "type": "圣十字型"}, {"name": "小皮球", "type": "弹弹型"}],
  贝古斯: [{"name": "立方人", "type": "机核型"}, {"name": "雪影娃娃", "type": "霜华型"}, {"name": "月牙雪熊", "type": "雪熊型"}],
  雅丹鬃: [{"name": "燃薪虫", "type": "烬燃型"}, {"name": "疾光千兽", "type": "极光型"}, {"name": "酷拉", "type": "雷动型"}],
  火神: [{"name": "水灵", "type": "互补型"}, {"name": "罗隐", "type": "稳定型"}, {"name": "酷拉", "type": "活跃型"}],
  水灵: [{"name": "火神", "type": "互补型"}, {"name": "魔力猫", "type": "守护型"}, {"name": "罗隐", "type": "踏实型"}],
  魔力猫: [{"name": "水灵", "type": "治愈型"}, {"name": "火神", "type": "激励型"}, {"name": "罗隐", "type": "陪伴型"}],
  圣羽翼王: [{"name": "酷拉", "type": "冒险型"}, {"name": "火神", "type": "活力型"}, {"name": "魔力猫", "type": "守护型"}],
  罗隐: [{"name": "水灵", "type": "温柔型"}, {"name": "魔力猫", "type": "陪伴型"}, {"name": "火神", "type": "突破型"}],
  龙息帕尔: [{"name": "雪影娃娃", "type": "默契型"}, {"name": "酷拉", "type": "启发型"}, {"name": "火神", "type": "温暖型"}],
  迪莫: [{"name": "火神", "type": "活力型"}, {"name": "水灵", "type": "温柔型"}, {"name": "龙息帕尔", "type": "照亮型"}],
  皇家狮鹫: [{"name": "圣羽翼王", "type": "天空型"}, {"name": "酷拉", "type": "闪电型"}, {"name": "冰封怨灵", "type": "冷静型"}],
  幻影灵菇: [{"name": "绒仙子", "type": "温柔型"}, {"name": "魔力猫", "type": "静谧型"}, {"name": "圣羽翼王", "type": "梦想型"}],
  烈火守护: [{"name": "罗隐", "type": "稳重型"}, {"name": "火神", "type": "火力型"}, {"name": "冰封怨灵", "type": "冷静型"}],
  冰封怨灵: [{"name": "雪影娃娃", "type": "默契型"}, {"name": "龙息帕尔", "type": "深沉型"}, {"name": "火神", "type": "融化型"}],
  尖嘴狐仙: [{"name": "火神", "type": "闪耀型"}, {"name": "迪莫", "type": "温暖型"}, {"name": "酷拉", "type": "活力型"}],
  寂灭骨龙: [{"name": "火神", "type": "王者型"}, {"name": "罗隐", "type": "忠诚型"}, {"name": "水灵", "type": "制衡型"}],
  瞌睡王: [{"name": "魔力猫", "type": "慵懒型"}, {"name": "龙息帕尔", "type": "夜猫型"}, {"name": "火神", "type": "闹钟型"}],
};

export const results: Record<string, PetResult> = {
  利灯鱼: {
    name: '利灯鱼',
    type: '孤灯型',
    mbti: 'INTJ-R',
    emoji: '🐟',
    el: '水',
    img: 'https://patchwiki.biligame.com/images/rocom/f/f0/q3g76bthejmlv9o6phrchq0cpdlfzhy.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/f/f0/q3g76bthejmlv9o6phrchq0cpdlfzhy.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/2/21/rgd2axhi4ehoa0u962goi1zir48sffs.png',
    intro: '我在深海里点了一盏灯，等一个不会来的人。',
    desc: '我在三千米深的海沟里点了一盏灯。\n\n没有鱼群经过，没有洋流回应，只有我自己知道这盏灯为什么亮着。你说我孤独？不，我只是把光省给了唯一值得照亮的那个影子——哪怕它永远不会来。',
    tags: ["异色", "稀有", "孤独", "发光"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 2, 'W': 2},
    compat: defaultCompats['利灯鱼'],
  },
  夜枭: {
    name: '夜枭',
    type: '夜行型',
    mbti: 'ISTP-R',
    emoji: '🦉',
    el: '翼',
    img: 'https://patchwiki.biligame.com/images/rocom/6/63/ff8hybk5g0efhfnva9476qaovcmdl2i.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/6/63/ff8hybk5g0efhfnva9476qaovcmdl2i.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/3/32/lonl2w0yolffs34iwh5gxtqjqgq7ukm.png',
    intro: '白天属于世界，夜晚属于我。',
    desc: '白天的世界太吵了，吵到连自己的心跳都听不见。\n\n只有到了晚上，当所有人都睡了，我才敢把耳朵贴在地面上，听大地深处的声音。我不是不合群，我只是找到了更适合我的时间区。',
    tags: ["异色", "稀有", "夜行", "敏锐"],
    expect: {'E': 1, 'S': 2, 'B': 1, 'M': 1, 'W': 3},
    compat: defaultCompats['夜枭'],
  },
  恶魔狼: {
    name: '恶魔狼',
    type: '暗牙型',
    mbti: 'ESTP-R',
    emoji: '🐺',
    el: '恶魔',
    img: 'https://patchwiki.biligame.com/images/rocom/6/6a/8rz167blfbrzzs44u5mq8a0k7im6ap8.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/6/6a/8rz167blfbrzzs44u5mq8a0k7im6ap8.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/8/8c/d7bp7k8moy6w7pt6zm7l7epnqfx3kja.png',
    intro: '我不需要被理解，我只需要被敬畏。',
    desc: '撕碎或者被撕碎——这就是唯一的法则。\n\n我不谈判，不解释，不道歉。我的獠牙就是我的语言，我的爪痕就是我的签名。你可以恨我，但你不能无视我。在这个人人都在表演温顺的世界里，我选择做那个露出牙齿的混蛋。',
    tags: ["异色", "稀有", "叛逆", "野性"],
    expect: {'E': 3, 'S': 2, 'B': 3, 'M': 3, 'W': 2},
    compat: defaultCompats['恶魔狼'],
  },
  燃薪虫: {
    name: '燃薪虫',
    type: '烬燃型',
    mbti: 'ENFP-R',
    emoji: '🐛',
    el: '火',
    img: 'https://patchwiki.biligame.com/images/rocom/8/88/h3usttwjdsh4q3vn5t2st0g24nlv4go.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/8/88/h3usttwjdsh4q3vn5t2st0g24nlv4go.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/7/70/5gtw6kq6lpxq9uorw3vh4syo5h87fpl.png',
    intro: '即使化为灰烬，也要燃烧到最后。',
    desc: '即使化成灰，我也要在灰烬里再烧一次。\n\n平庸对我来说不是选择，是侮辱。别人说我极端，但他们不知道——只有极致的燃烧，才能让我感觉到自己真的存在过。我不在乎能烧多久，我只在乎烧得够不够亮。',
    tags: ["异色", "稀有", "燃烧", "极端"],
    expect: {'E': 3, 'S': 3, 'B': 2, 'M': 3, 'W': 3},
    compat: defaultCompats['燃薪虫'],
  },
  疾光千兽: {
    name: '疾光千兽',
    type: '极光型',
    mbti: 'ENTJ-R',
    emoji: '⚡',
    el: '电',
    img: 'https://patchwiki.biligame.com/images/rocom/b/ba/18st3mhvamod8xnva8rybnme9cgkc9b.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/b/ba/18st3mhvamod8xnva8rybnme9cgkc9b.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/1/11/j5stbkoyuovlj9ybmm1c0jua72l3d08.png',
    intro: '你看到的我，已经是我的残影了。',
    desc: '你看到的我的背影，其实是三秒前的残影。\n\n我不是不想等你们，是我实在受不了按别人的节奏走路。等我的人最终都会放弃，但我不会为了被理解而放慢半步。孤独是速度的副作用，我认了。',
    tags: ["异色", "稀有", "极速", "超前"],
    expect: {'E': 2, 'S': 1, 'B': 2, 'M': 2, 'W': 2},
    compat: defaultCompats['疾光千兽'],
  },
  窃光蚊: {
    name: '窃光蚊',
    type: '窃影型',
    mbti: 'INTP-R',
    emoji: '🦟',
    el: '虫',
    img: 'https://patchwiki.biligame.com/images/rocom/e/ee/9ftuu9x2yo8twq5h8lthgnelas283kg.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/e/ee/9ftuu9x2yo8twq5h8lthgnelas283kg.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/8/85/9ig4qqyybrjarfg75qtsd3ehj4sk1kc.png',
    intro: '我取走一点光，没人会发现的。',
    desc: '最好的猎手，从来不发出声音。\n\n我取走你的一缕光，你甚至不会察觉少了什么。等你发现的时候，我已经在下一个阴影里吃饱了。低调不是懦弱，是最高级的进攻策略——毕竟，谁会防备一只蚊子呢？',
    tags: ["异色", "稀有", "隐秘", "精明"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 1, 'W': 2},
    compat: defaultCompats['窃光蚊'],
  },
  立方人: {
    name: '立方人',
    type: '机核型',
    mbti: 'ISTJ-A',
    emoji: '🤖',
    el: '机械',
    img: 'https://patchwiki.biligame.com/images/rocom/d/d3/40n8738yvp681xgekmv094toaqjthrg.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/0/09/fnsx2e888qucax28zooe75tenxxgmkx.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/d/d3/40n8738yvp681xgekmv094toaqjthrg.png',
    intro: '情感是bug，逻辑才是feature。',
    desc: '情感模块未响应。逻辑运算正常。\n\n你不是没有感受，你只是把感受也当成了数据输入。喜欢一个人？先列出十七个变量做回归分析。想哭？先评估哭的ROI。这种「无情」让你 missed 掉一些浪漫，但也让你避开了一大堆麻烦。',
    tags: ["理性", "机械", "精准", "无情"],
    expect: {'E': 2, 'S': 2, 'B': 1, 'M': 1, 'W': 3},
    compat: defaultCompats['立方人'],
  },
  粉耳星兔: {
    name: '粉耳星兔',
    type: '萌星型',
    mbti: 'ENFP-R2',
    emoji: '🐰',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/1/12/dfrmcjhoft7x9ne5xiint27n3ustjzx.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/1/12/dfrmcjhoft7x9ne5xiint27n3ustjzx.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/3/31/6k9hvh0m5rdvbgleimeptf3xj8we5cg.png',
    intro: '别看我可爱，我也是会咬人的。',
    desc: '「哎呀我什么都不懂的啦~」——这句话我说得比谁都顺口。\n\n但你要是信了，你就输了。我的耳朵是粉色的，但我的牙齿是钢的。用软萌的外表降低你的警惕，然后用你没想到的方式赢你。这叫策略，不叫欺骗。',
    tags: ["异色", "稀有", "可爱", "反差"],
    expect: {'E': 3, 'S': 3, 'B': 1, 'M': 3, 'W': 3},
    compat: defaultCompats['粉耳星兔'],
  },
  红绒十字: {
    name: '红绒十字',
    type: '圣十字型',
    mbti: 'ISFJ-R',
    emoji: '✝️',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/c/c1/1i2n00tjjxrhc3x9p39hrg4kxujapoh.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/c/c1/1i2n00tjjxrhc3x9p39hrg4kxujapoh.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/0/0a/ipl5brmemkyidval7taro7b540zmzqm.png',
    intro: '我守护的不是信仰，是我自己的选择。',
    desc: '我可以为你挡一刀，但我不会替你撒谎。\n\n我的温柔不是无限供应的慈善，是带条件的恩典。踩过我的底线一次，你就永远失去了被我温柔对待的资格。这不是冷漠，是我对「善良」这两个字最后的尊重。',
    tags: ["异色", "稀有", "信仰", "守护"],
    expect: {'E': 2, 'S': 2, 'B': 2, 'M': 2, 'W': 3},
    compat: defaultCompats['红绒十字'],
  },
  绒仙子: {
    name: '绒仙子',
    type: '绒暖型',
    mbti: 'ISFP',
    emoji: '🧚',
    el: '妖精',
    img: 'https://patchwiki.biligame.com/images/rocom/1/11/5wpjm56l3vhq88hfw8mjvagpk1paqz8.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/2/2a/nynxiyjn07oseu31p6o5z8crn5i6dx0.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/1/11/5wpjm56l3vhq88hfw8mjvagpk1paqz8.png',
    intro: '柔软不是弱点，是我的超能力。',
    desc: '你收集黄昏、收集雨声、收集一切没有实用价值但让你心动的东西。\n\n在这个用「效率」和「产出」衡量一切的世界里，你是一个不合时宜的收藏家。别人笑你没用，但你拥有的那些「没用」的东西，恰恰是你灵魂里最值钱的部分。',
    tags: ["温柔", "艺术", "敏感", "治愈"],
    expect: {'E': 2, 'S': 1, 'B': 1, 'M': 2, 'W': 3},
    compat: defaultCompats['绒仙子'],
  },
  酷拉: {
    name: '酷拉',
    type: '雷动型',
    mbti: 'ENTP',
    emoji: '⚡',
    el: '电',
    img: 'https://patchwiki.biligame.com/images/rocom/b/b0/0a4re28no5axjfaazy5qpysri7a42jp.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/8/8e/f72t0l1mbisw4ehkivz7pdpbcqkosus.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/b/b0/0a4re28no5axjfaazy5qpysri7a42jp.png',
    intro: '规则？那是用来打破的。',
    desc: '规则是上一批人写的，而你是来重写规则的那一批。\n\n别人还在查攻略的时候，你已经把副本拆了重新组装。你的脑子里没有「标准答案」这四个字，只有「还能不能更好玩」。跟你待久了，保守的人会觉得累，但有趣的人会觉得这才是活着。',
    tags: ["机智", "活跃", "创意", "叛逆"],
    expect: {'E': 3, 'S': 3, 'B': 1, 'M': 3, 'W': 2},
    compat: defaultCompats['酷拉'],
  },
  雪影娃娃: {
    name: '雪影娃娃',
    type: '霜华型',
    mbti: 'INTJ',
    emoji: '❄️',
    el: '冰',
    img: 'https://patchwiki.biligame.com/images/rocom/9/9e/62t72i1tuv4mwq8abr9ppobh6m5ljlv.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/1/12/ixakouy2o2kjsl0ytlhtdzhoukgoq3o.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/9/9e/62t72i1tuv4mwq8abr9ppobh6m5ljlv.png',
    intro: '冷静是我的铠甲，理性是我的武器。',
    desc: '别人在群里聊得热火朝天，你在心里给他们每个人都打了分——不是恶意，只是本能的过滤系统。\n\n你不需要被理解，你需要的是不被打扰。你的社交圈小得像冰箱里的灯，只在开门的时候才亮，但足够照亮你真正在乎的那几样东西。',
    tags: ["理性", "独立", "战略家", "完美主义"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 1, 'W': 3},
    compat: defaultCompats['雪影娃娃'],
  },
  奇丽花: {
    name: '奇丽花',
    type: '花语型',
    mbti: 'INFP',
    emoji: '🌸',
    el: '草',
    img: 'https://patchwiki.biligame.com/images/rocom/8/8c/dbgfehb9vsrkwnn1jkxtibxciapkdur.png',
    intro: '我不说话的时候，才是我最吵的时候。',
    desc: '你不需要说话，光是站在那里就是一道风景。\n\n别人急着表达自己，你只是安静地开花。但你知道——最持久的影响力，从来都不是喊出来的，是开出来的。你的存在本身就是一种回答。',
    tags: ["安静", "美丽", "神秘", "自然"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 2, 'W': 3},
    compat: defaultCompats['奇丽花'],
  },
  小皮球: {
    name: '小皮球',
    type: '弹弹型',
    mbti: 'ESFP',
    emoji: '🔵',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/1/11/coplggyd0xwtvzzkw5d1say369yg1oy.png',
    intro: '我滚到哪里，快乐就跟到哪里。',
    desc: '你不需要目的地，滚动的过程本身就是意义。\n\n别人问你「你要去哪」，你说「不知道，但我很开心」。这种「无目的的快乐」在成年人眼里是不成熟，在你眼里是天赋。你被弹开一百次，第一百零一次照样弹回来。',
    tags: ["活泼", "可爱", "乐天", "弹性"],
    expect: {'E': 3, 'S': 1, 'B': 2, 'M': 1, 'W': 2},
    compat: defaultCompats['小皮球'],
  },
  月牙雪熊: {
    name: '月牙雪熊',
    type: '雪熊型',
    mbti: 'ISTJ',
    emoji: '🐻‍❄️',
    el: '冰',
    img: 'https://patchwiki.biligame.com/images/rocom/5/5d/0cskl2u4wneivk2icntkrcaiwuwv4yq.png',
    intro: '冬天不是我的敌人，是我的被子。',
    desc: '你走路很慢，但每一步都踩得很实。\n\n别人急着赶路，你在雪地里留下一串整齐的脚印。你不怕冷，因为你的身体里有一座永远不会熄灭的壁炉——只是外人看不到。',
    tags: ["沉稳", "冬眠", "白色", "耐寒"],
    expect: {'E': 1, 'S': 2, 'B': 2, 'M': 1, 'W': 1},
    compat: defaultCompats['月牙雪熊'],
  },
  格兰球: {
    name: '格兰球',
    type: '滚动型',
    mbti: 'ESFJ',
    emoji: '🎱',
    el: '石',
    img: 'https://patchwiki.biligame.com/images/rocom/6/6c/ti7vsccgrnfmugk27891cc9726d15j5.png',
    intro: '滚得快不重要，滚得开心才重要。',
    desc: '你是人群里的润滑剂，冲突到你这里就自动滑过去了。\n\n别人争得头破血流，你只是滚过去，把两边的棱角都磨平。你的圆滑不是虚伪，是你真的不想看到任何人受伤。',
    tags: ["滚动", "社交", "快乐", "圆滑"],
    expect: {'E': 2, 'S': 3, 'B': 2, 'M': 1, 'W': 1},
    compat: defaultCompats['格兰球'],
  },
  獠牙猪: {
    name: '獠牙猪',
    type: '冲锋型',
    mbti: 'ESTP',
    emoji: '🐗',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/e/e7/9k7bizwcoun5u7cvgvqgchfd9dmyxou.png',
    intro: '我的獠牙不是为了吓人，是为了开路。',
    desc: '前面有墙？撞开。前面有河？蹚过去。\n\n你不是没脑子，你只是觉得想太多浪费时间。你的冲锋替团队省掉了无数个「再讨论一下」的会议。当然，你也撞坏过不少不该撞的东西——但那又怎样，至少你动了。',
    tags: ["冲锋", "勇猛", "野猪", "无畏"],
    expect: {'E': 3, 'S': 1, 'B': 3, 'M': 2, 'W': 1},
    compat: defaultCompats['獠牙猪'],
  },
  落陨星兔: {
    name: '落陨星兔',
    type: '陨星型',
    mbti: 'INFJ',
    emoji: '🌠',
    el: '光',
    img: 'https://patchwiki.biligame.com/images/rocom/8/86/jeo10wvmxho14u7cdmib8272dqfuzpr.png',
    intro: '我是一颗选择坠落的星星，只为照亮你。',
    desc: '你明明可以留在天上，却选择坠落到人间。\n\n别人笑你傻，说高处多好。但你只是想离你想照亮的人近一点。坠落的过程很痛，但你不在乎——你本来就不是为了舒服才来的。',
    tags: ["星空", "坠落", "兔子", "光芒"],
    expect: {'E': 1, 'S': 3, 'B': 1, 'M': 2, 'W': 1},
    compat: defaultCompats['落陨星兔'],
  },
  贝古斯: {
    name: '贝古斯',
    type: '古械型',
    mbti: 'INTJ',
    emoji: '🏛️',
    el: '机械',
    img: 'https://patchwiki.biligame.com/images/rocom/0/0d/8cvnsom0kdicxcvjnut1lewivnuxgr2.png',
    intro: '齿轮转动了三千年，只为等一个懂我的人。',
    desc: '你不是过时，你是太超前了。\n\n别人的脑子装的是 App，你的脑子里装的是操作系统。你说话很慢，因为每个词都经过了三层加密。等你终于开口的时候，话题已经换三轮了——所以你选择不说。',
    tags: ["古代", "机械", "沉默", "永恒"],
    expect: {'E': 2, 'S': 1, 'B': 3, 'M': 1, 'W': 2},
    compat: defaultCompats['贝古斯'],
  },
  雅丹鬃: {
    name: '雅丹鬃',
    type: '风鬃型',
    mbti: 'ENFP',
    emoji: '🌬️',
    el: '翼',
    img: 'https://patchwiki.biligame.com/images/rocom/c/c2/1qy2ib6i9lr8p6c9gh8mfuo0df9a1tb.png',
    intro: '风从我的鬃毛间穿过，带走了所有的秘密。',
    desc: '你路过的地方，连空气都变得不一样了。\n\n不是你在追风，是风在追你。你不需要扎根，因为你本身就是流动的。别人问你「你的家在哪」，你说「下一个风向」。',
    tags: ["风", "自由", "鬃毛", "轻盈"],
    expect: {'E': 3, 'S': 2, 'B': 1, 'M': 1, 'W': 1},
    compat: defaultCompats['雅丹鬃'],
  },
  火神: {
    name: '火神',
    type: '烈焰型',
    mbti: 'ENFJ',
    emoji: '🔥',
    el: '火',
    img: 'https://patchwiki.biligame.com/images/rocom/4/4f/627a47xjvghn9okifk66vhsx4uv7101.png',
    intro: '烈焰焚尽世间阴霾，我是照亮黑夜的第一束光。',
    desc: '你是天生的领袖，走到哪都能点燃周围人的热情。\n\n行动力是你的超能力，犹豫是你的奢侈品。当所有人还在讨论方案的时候，你已经把第一步走出去了——而且大概率，是对的。',
    tags: ["领导力", "热血", "行动派", "感染力"],
    expect: {'E': 3, 'S': 3, 'B': 3, 'M': 3, 'W': 2},
    compat: defaultCompats['火神'],
  },
  水灵: {
    name: '水灵',
    type: '潮汐型',
    mbti: 'ISFJ',
    emoji: '💧',
    el: '水',
    img: 'https://patchwiki.biligame.com/images/rocom/5/50/33by7ml0nsrsxxq1l8l2uj4izqnuwpd.png',
    intro: '温柔不是软弱，是包容万物的力量。',
    desc: '你是团队里最安静却最不可或缺的存在。\n\n你的共情能力让你成为朋友的心事树洞。你不一定话最多，但每一句都说在点上。别人记得你，是因为你让他们感到被看见。',
    tags: ["温柔", "治愈", "可靠", "细腻"],
    expect: {'E': 1, 'S': 2, 'B': 1, 'M': 2, 'W': 2},
    compat: defaultCompats['水灵'],
  },
  魔力猫: {
    name: '魔力猫',
    type: '森灵型',
    mbti: 'INFJ',
    emoji: '🌿',
    el: '草',
    img: 'https://patchwiki.biligame.com/images/rocom/3/33/p4l4i0xh8rzj0mosp9sgw4qjfvlbl0r.png',
    intro: '在无人问津处，我长成一片森林。',
    desc: '你安静而坚韧，有着外人难以触及的内心世界。\n\n你的耐心是你的超能力。别人三分钟热度的事，你可以坚持三年。等他们回头看你的时候，你已经长成了他们永远到不了的样子。',
    tags: ["内敛", "坚韧", "理想主义", "忠诚"],
    expect: {'E': 1, 'S': 2, 'B': 2, 'M': 2, 'W': 3},
    compat: defaultCompats['魔力猫'],
  },
  圣羽翼王: {
    name: '圣羽翼王',
    type: '苍穹型',
    mbti: 'ENFP',
    emoji: '🦅',
    el: '翼',
    img: 'https://patchwiki.biligame.com/images/rocom/4/40/lbxi6r2yicliuipn8dp7n5pk90xfjo4.png',
    intro: '天空没有边界，我的心也是。',
    desc: '你热爱自由，讨厌被规则和框架束缚。\n\n你像一只候鸟，永远在追寻新的风景和体验。你不会为了"稳定"放弃远方，因为你知道：天花板低的房间里，住不下你的翅膀。',
    tags: ["自由", "乐观", "好奇心", "浪漫"],
    expect: {'E': 3, 'S': 2, 'B': 2, 'M': 3, 'W': 3},
    compat: defaultCompats['圣羽翼王'],
  },
  罗隐: {
    name: '罗隐',
    type: '岩盾型',
    mbti: 'ISTJ',
    emoji: '🪨',
    el: '石',
    img: 'https://patchwiki.biligame.com/images/rocom/3/38/495925un1xk6eioymvva969ahadlk3m.png',
    intro: '我不动如山，但我会一直在。',
    desc: '你务实、可靠、言出必行。\n\n在朋友眼中你是最值得信赖的存在。你不会说很多漂亮话，但你答应的事一定会做到。在这个浮夸的世界里，你的"靠谱"已经是一种稀缺品。',
    tags: ["稳重", "可靠", "务实", "责任感"],
    expect: {'E': 1, 'S': 2, 'B': 1, 'M': 1, 'W': 2},
    compat: defaultCompats['罗隐'],
  },
  龙息帕尔: {
    name: '龙息帕尔',
    type: '幽影型',
    mbti: 'INTP',
    emoji: '👻',
    el: '幽灵',
    img: 'https://patchwiki.biligame.com/images/rocom/0/0f/q0bwy4syzqav082nqhy9tl7i8hsirz4.png',
    intro: '在阴影中，我看见了你们看不见的东西。',
    desc: '你独特而深沉，有着与众不同的思维方式。\n\n你的深度和智慧让人无法忽视。你不擅长解释自己——因为你想说的话，需要听得懂的人。其他人？让他们在浅滩自己玩去。',
    tags: ["神秘", "深邃", "独立", "创造力"],
    expect: {'E': 1, 'S': 1, 'B': 2, 'M': 1, 'W': 3},
    compat: defaultCompats['龙息帕尔'],
  },
  迪莫: {
    name: '迪莫',
    type: '光启型',
    mbti: 'ESFJ',
    emoji: '✨',
    el: '光',
    img: 'https://patchwiki.biligame.com/images/rocom/2/25/o64cvcxq1l6tlur77xjqbwx2s4imabd.png',
    intro: '有我在，就不会有人被留在黑暗里。',
    desc: '你是天生的守护者，身上自带一种让人安心的光芒。\n\n你的温暖是发自内心的本能——不是讨好，不是表演，就是看到别人难过你就难受。这种"圣母光环"有时会让你疲惫，但你从未想过关掉它。',
    tags: ["温暖", "守护", "善良", "奉献"],
    expect: {'E': 2, 'S': 3, 'B': 2, 'M': 2, 'W': 2},
    compat: defaultCompats['迪莫'],
  },
  皇家狮鹫: {
    name: '皇家狮鹫',
    type: '疾风型',
    mbti: 'ESTP',
    emoji: '🌪️',
    el: '翼',
    img: 'https://patchwiki.biligame.com/images/rocom/0/09/nji78x7xa58n2ye2yhkqgedpywia239.png',
    intro: '速度就是我的正义。',
    desc: '你信奉先做了再说，喜欢刺激、追求快感，讨厌拖泥带水。\n\n你的行动力让人惊叹。当别人还在 PPT 上画战略图的时候，你已经在战场上拿了第一血。你的格言是：完美是反应不过来的人才追求的。',
    tags: ["勇猛", "迅捷", "冒险", "冲动"],
    expect: {'E': 3, 'S': 2, 'B': 3, 'M': 2, 'W': 2},
    compat: defaultCompats['皇家狮鹫'],
  },
  幻影灵菇: {
    name: '幻影灵菇',
    type: '幻梦型',
    mbti: 'INFP',
    emoji: '🍄',
    el: '幽灵',
    img: 'https://patchwiki.biligame.com/images/rocom/0/0f/915lidbxavc7iprutynlt2z380lxb7x.png',
    intro: '现实太吵了，我在梦里盖了一座城堡。',
    desc: '你是一个活在内心世界的人，对美好的事物有着近乎偏执的追求。\n\n外面的人觉得你飘忽、不接地气——但他们不知道，你的脑海里住着一整个会下雨会开花的宇宙。现实是临时的，梦才是你的永居地址。',
    tags: ["梦幻", "敏感", "创造力", "理想主义"],
    expect: {'E': 1, 'S': 2, 'B': 1, 'M': 3, 'W': 3},
    compat: defaultCompats['幻影灵菇'],
  },
  烈火守护: {
    name: '烈火守护',
    type: '炽心型',
    mbti: 'ESTJ',
    emoji: '🔥',
    el: '火',
    img: 'https://patchwiki.biligame.com/images/rocom/3/36/8wp59h53ob7gllbz8yewg91ppibly6x.png',
    intro: '秩序就是火焰，烧尽一切混乱。',
    desc: '你是天生的指挥官，对效率和秩序有着近乎偏执的追求。\n\n炽热的火焰在你手中不是毁灭的工具，而是划定边界的光。你或许不是最强的那一个，但绝对是最让人安心的那一个——只要你在，就没有人敢越界。',
    deepDesc: '火系精灵里，多的是燃烧自己的疯子，少的是守护别人的将军——你属于后者。\n\n你的偏执从来不是为了赢，而是为了守住。规则之内的人或许从未察觉你的存在，但他们之所以能安心地过普通生活，是因为有你在边界处架起了那道无声的防火墙。',
    tags: ["纪律", "权威", "高效", "果断"],
    expect: {'E': 3, 'S': 2, 'B': 3, 'M': 2, 'W': 3},
    compat: defaultCompats['烈火守护'],
  },
  冰封怨灵: {
    name: '冰封怨灵',
    type: '冰魄型',
    mbti: 'ISTP',
    emoji: '❄️',
    el: '冰',
    img: 'https://patchwiki.biligame.com/images/rocom/2/20/kgz0l0h5v268zpumgfbqz7nhqtvgyey.png',
    intro: '我的冷静，是经历过风暴后的平静。',
    desc: '你冷静、独立、动手能力极强。\n\n你在混乱中反而最清醒。别人慌了你不慌，因为你早就在心里把所有可能的剧本演过一遍。情绪是消耗品，思考才是奢侈品——这是你与世界相处的方式。',
    tags: ["冷静", "精准", "独立", "技术控"],
    expect: {'E': 1, 'S': 1, 'B': 2, 'M': 1, 'W': 2},
    compat: defaultCompats['冰封怨灵'],
  },
  尖嘴狐仙: {
    name: '尖嘴狐仙',
    type: '狐魅型',
    mbti: 'ESFP',
    emoji: '🦊',
    el: '火',
    img: 'https://patchwiki.biligame.com/images/rocom/b/b1/gqbvamoe1ljcd3be988hlopoxdo44ak.png',
    intro: '全场目光，请集中在我这里。',
    desc: '你是天生的表演者，走到哪都能成为焦点。\n\n你的魅力是天生的，藏不住，也不想藏。你不是在炫耀——你只是天然就该被看见。世界不会主动给你舞台？没事，你站哪里哪里就是舞台。',
    tags: ["魅力", "表演", "热情", "活在当下"],
    expect: {'E': 3, 'S': 3, 'B': 2, 'M': 3, 'W': 2},
    compat: defaultCompats['尖嘴狐仙'],
  },
  寂灭骨龙: {
    name: '寂灭骨龙',
    type: '龙吟型',
    mbti: 'ENTJ',
    emoji: '🐉',
    el: '龙',
    img: 'https://patchwiki.biligame.com/images/rocom/3/31/g9815x8kx47nbavj9mcolhexofrpulc.png',
    intro: '臣服，或者毁灭。没有第三个选项。',
    desc: '你是天生的统治者，自带一种让人不寒而栗的威严。\n\n你对目标有着近乎疯狂的执着。你不需要别人喜欢你——你需要的是结果。你的字典里只有"要"和"不要"，没有"也许"。',
    tags: ["霸气", "统治", "野心", "冷酷"],
    expect: {'E': 3, 'S': 2, 'B': 3, 'M': 3, 'W': 3},
    compat: defaultCompats['寂灭骨龙'],
  },
  瞌睡王: {
    name: '瞌睡王',
    type: '懒神型',
    mbti: 'INTP-A',
    emoji: '😴',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/a/a2/64947rnxu8ncihl37rqldr3653bg57n.png',
    intro: '别吵，我在思考人生……Zzz……',
    desc: '你测出了全王国最稀有的懒神型。\n\n你的座右铭是「能躺着绝不坐着」，但你的大脑其实一直在高速运转。你不是真的懒——你只是把"省下来的力气"花在了真正重要的事情上。比如，发呆。',
    tags: ["慵懒", "大智若愚", "随性", "反差萌"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 1, 'W': 1},
    compat: defaultCompats['瞌睡王'],
  },
};

export const shinyPets: Record<string, ShinyPet> = {
  利灯鱼: {
    name: '利灯鱼',
    type: '孤灯型',
    mbti: 'INTJ-R',
    emoji: '🐟',
    el: '水',
    img: 'https://patchwiki.biligame.com/images/rocom/2/21/rgd2axhi4ehoa0u962goi1zir48sffs.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/f/f0/q3g76bthejmlv9o6phrchq0cpdlfzhy.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/2/21/rgd2axhi4ehoa0u962goi1zir48sffs.png',
    intro: '我在深海里点了一盏灯，等一个不会来的人。',
    desc: '我在三千米深的海沟里点了一盏灯。\n\n没有鱼群经过，没有洋流回应，只有我自己知道这盏灯为什么亮着。你说我孤独？不，我只是把光省给了唯一值得照亮的那个影子——哪怕它永远不会来。',
    tags: ["异色", "稀有", "孤独", "发光"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 2, 'W': 2},
    compat: defaultCompats['利灯鱼'],
    shinyRate: 0.08,
  },
  夜枭: {
    name: '夜枭',
    type: '夜行型',
    mbti: 'ISTP-R',
    emoji: '🦉',
    el: '翼',
    img: 'https://patchwiki.biligame.com/images/rocom/3/32/lonl2w0yolffs34iwh5gxtqjqgq7ukm.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/6/63/ff8hybk5g0efhfnva9476qaovcmdl2i.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/3/32/lonl2w0yolffs34iwh5gxtqjqgq7ukm.png',
    intro: '白天属于世界，夜晚属于我。',
    desc: '白天的世界太吵了，吵到连自己的心跳都听不见。\n\n只有到了晚上，当所有人都睡了，我才敢把耳朵贴在地面上，听大地深处的声音。我不是不合群，我只是找到了更适合我的时间区。',
    tags: ["异色", "稀有", "夜行", "敏锐"],
    expect: {'E': 1, 'S': 2, 'B': 1, 'M': 1, 'W': 3},
    compat: defaultCompats['夜枭'],
    shinyRate: 0.12,
  },
  恶魔狼: {
    name: '恶魔狼',
    type: '暗牙型',
    mbti: 'ESTP-R',
    emoji: '🐺',
    el: '恶魔',
    img: 'https://patchwiki.biligame.com/images/rocom/8/8c/d7bp7k8moy6w7pt6zm7l7epnqfx3kja.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/6/6a/8rz167blfbrzzs44u5mq8a0k7im6ap8.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/8/8c/d7bp7k8moy6w7pt6zm7l7epnqfx3kja.png',
    intro: '我不需要被理解，我只需要被敬畏。',
    desc: '撕碎或者被撕碎——这就是唯一的法则。\n\n我不谈判，不解释，不道歉。我的獠牙就是我的语言，我的爪痕就是我的签名。你可以恨我，但你不能无视我。在这个人人都在表演温顺的世界里，我选择做那个露出牙齿的混蛋。',
    tags: ["异色", "稀有", "叛逆", "野性"],
    expect: {'E': 3, 'S': 2, 'B': 3, 'M': 3, 'W': 2},
    compat: defaultCompats['恶魔狼'],
    shinyRate: 0.05,
  },
  燃薪虫: {
    name: '燃薪虫',
    type: '烬燃型',
    mbti: 'ENFP-R',
    emoji: '🐛',
    el: '火',
    img: 'https://patchwiki.biligame.com/images/rocom/7/70/5gtw6kq6lpxq9uorw3vh4syo5h87fpl.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/8/88/h3usttwjdsh4q3vn5t2st0g24nlv4go.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/7/70/5gtw6kq6lpxq9uorw3vh4syo5h87fpl.png',
    intro: '即使化为灰烬，也要燃烧到最后。',
    desc: '即使化成灰，我也要在灰烬里再烧一次。\n\n平庸对我来说不是选择，是侮辱。别人说我极端，但他们不知道——只有极致的燃烧，才能让我感觉到自己真的存在过。我不在乎能烧多久，我只在乎烧得够不够亮。',
    tags: ["异色", "稀有", "燃烧", "极端"],
    expect: {'E': 3, 'S': 3, 'B': 2, 'M': 3, 'W': 3},
    compat: defaultCompats['燃薪虫'],
    shinyRate: 0.09,
  },
  疾光千兽: {
    name: '疾光千兽',
    type: '极光型',
    mbti: 'ENTJ-R',
    emoji: '⚡',
    el: '电',
    img: 'https://patchwiki.biligame.com/images/rocom/1/11/j5stbkoyuovlj9ybmm1c0jua72l3d08.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/b/ba/18st3mhvamod8xnva8rybnme9cgkc9b.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/1/11/j5stbkoyuovlj9ybmm1c0jua72l3d08.png',
    intro: '你看到的我，已经是我的残影了。',
    desc: '你看到的我的背影，其实是三秒前的残影。\n\n我不是不想等你们，是我实在受不了按别人的节奏走路。等我的人最终都会放弃，但我不会为了被理解而放慢半步。孤独是速度的副作用，我认了。',
    tags: ["异色", "稀有", "极速", "超前"],
    expect: {'E': 2, 'S': 1, 'B': 2, 'M': 2, 'W': 2},
    compat: defaultCompats['疾光千兽'],
    shinyRate: 0.07,
  },
  窃光蚊: {
    name: '窃光蚊',
    type: '窃影型',
    mbti: 'INTP-R',
    emoji: '🦟',
    el: '虫',
    img: 'https://patchwiki.biligame.com/images/rocom/8/85/9ig4qqyybrjarfg75qtsd3ehj4sk1kc.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/e/ee/9ftuu9x2yo8twq5h8lthgnelas283kg.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/8/85/9ig4qqyybrjarfg75qtsd3ehj4sk1kc.png',
    intro: '我取走一点光，没人会发现的。',
    desc: '最好的猎手，从来不发出声音。\n\n我取走你的一缕光，你甚至不会察觉少了什么。等你发现的时候，我已经在下一个阴影里吃饱了。低调不是懦弱，是最高级的进攻策略——毕竟，谁会防备一只蚊子呢？',
    tags: ["异色", "稀有", "隐秘", "精明"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 1, 'W': 2},
    compat: defaultCompats['窃光蚊'],
    shinyRate: 0.11,
  },
  立方人: {
    name: '立方人',
    type: '机核型',
    mbti: 'ISTJ-A',
    emoji: '🤖',
    el: '机械',
    img: 'https://patchwiki.biligame.com/images/rocom/d/d3/40n8738yvp681xgekmv094toaqjthrg.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/0/09/fnsx2e888qucax28zooe75tenxxgmkx.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/d/d3/40n8738yvp681xgekmv094toaqjthrg.png',
    intro: '情感是bug，逻辑才是feature。',
    desc: '情感模块未响应。逻辑运算正常。\n\n你不是没有感受，你只是把感受也当成了数据输入。喜欢一个人？先列出十七个变量做回归分析。想哭？先评估哭的ROI。这种「无情」让你 missed 掉一些浪漫，但也让你避开了一大堆麻烦。',
    tags: ["理性", "机械", "精准", "无情"],
    expect: {'E': 2, 'S': 2, 'B': 1, 'M': 1, 'W': 3},
    compat: defaultCompats['立方人'],
    shinyRate: 0.15,
  },
  粉耳星兔: {
    name: '粉耳星兔',
    type: '萌星型',
    mbti: 'ENFP-R2',
    emoji: '🐰',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/3/31/6k9hvh0m5rdvbgleimeptf3xj8we5cg.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/1/12/dfrmcjhoft7x9ne5xiint27n3ustjzx.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/3/31/6k9hvh0m5rdvbgleimeptf3xj8we5cg.png',
    intro: '别看我可爱，我也是会咬人的。',
    desc: '「哎呀我什么都不懂的啦~」——这句话我说得比谁都顺口。\n\n但你要是信了，你就输了。我的耳朵是粉色的，但我的牙齿是钢的。用软萌的外表降低你的警惕，然后用你没想到的方式赢你。这叫策略，不叫欺骗。',
    tags: ["异色", "稀有", "可爱", "反差"],
    expect: {'E': 3, 'S': 3, 'B': 1, 'M': 3, 'W': 3},
    compat: defaultCompats['粉耳星兔'],
    shinyRate: 0.06,
  },
  红绒十字: {
    name: '红绒十字',
    type: '圣十字型',
    mbti: 'ISFJ-R',
    emoji: '✝️',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/0/0a/ipl5brmemkyidval7taro7b540zmzqm.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/c/c1/1i2n00tjjxrhc3x9p39hrg4kxujapoh.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/0/0a/ipl5brmemkyidval7taro7b540zmzqm.png',
    intro: '我守护的不是信仰，是我自己的选择。',
    desc: '我可以为你挡一刀，但我不会替你撒谎。\n\n我的温柔不是无限供应的慈善，是带条件的恩典。踩过我的底线一次，你就永远失去了被我温柔对待的资格。这不是冷漠，是我对「善良」这两个字最后的尊重。',
    tags: ["异色", "稀有", "信仰", "守护"],
    expect: {'E': 2, 'S': 2, 'B': 2, 'M': 2, 'W': 3},
    compat: defaultCompats['红绒十字'],
    shinyRate: 0.04,
  },
  绒仙子: {
    name: '绒仙子',
    type: '绒暖型',
    mbti: 'ISFP',
    emoji: '🧚',
    el: '妖精',
    img: 'https://patchwiki.biligame.com/images/rocom/1/11/5wpjm56l3vhq88hfw8mjvagpk1paqz8.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/2/2a/nynxiyjn07oseu31p6o5z8crn5i6dx0.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/1/11/5wpjm56l3vhq88hfw8mjvagpk1paqz8.png',
    intro: '柔软不是弱点，是我的超能力。',
    desc: '你收集黄昏、收集雨声、收集一切没有实用价值但让你心动的东西。\n\n在这个用「效率」和「产出」衡量一切的世界里，你是一个不合时宜的收藏家。别人笑你没用，但你拥有的那些「没用」的东西，恰恰是你灵魂里最值钱的部分。',
    tags: ["温柔", "艺术", "敏感", "治愈"],
    expect: {'E': 2, 'S': 1, 'B': 1, 'M': 2, 'W': 3},
    compat: defaultCompats['绒仙子'],
    shinyRate: 0.1,
  },
  酷拉: {
    name: '酷拉',
    type: '雷动型',
    mbti: 'ENTP',
    emoji: '⚡',
    el: '电',
    img: 'https://patchwiki.biligame.com/images/rocom/b/b0/0a4re28no5axjfaazy5qpysri7a42jp.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/8/8e/f72t0l1mbisw4ehkivz7pdpbcqkosus.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/b/b0/0a4re28no5axjfaazy5qpysri7a42jp.png',
    intro: '规则？那是用来打破的。',
    desc: '规则是上一批人写的，而你是来重写规则的那一批。\n\n别人还在查攻略的时候，你已经把副本拆了重新组装。你的脑子里没有「标准答案」这四个字，只有「还能不能更好玩」。跟你待久了，保守的人会觉得累，但有趣的人会觉得这才是活着。',
    tags: ["机智", "活跃", "创意", "叛逆"],
    expect: {'E': 3, 'S': 3, 'B': 1, 'M': 3, 'W': 2},
    compat: defaultCompats['酷拉'],
    shinyRate: 0.13,
  },
  雪影娃娃: {
    name: '雪影娃娃',
    type: '霜华型',
    mbti: 'INTJ',
    emoji: '❄️',
    el: '冰',
    img: 'https://patchwiki.biligame.com/images/rocom/9/9e/62t72i1tuv4mwq8abr9ppobh6m5ljlv.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/1/12/ixakouy2o2kjsl0ytlhtdzhoukgoq3o.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/9/9e/62t72i1tuv4mwq8abr9ppobh6m5ljlv.png',
    intro: '冷静是我的铠甲，理性是我的武器。',
    desc: '别人在群里聊得热火朝天，你在心里给他们每个人都打了分——不是恶意，只是本能的过滤系统。\n\n你不需要被理解，你需要的是不被打扰。你的社交圈小得像冰箱里的灯，只在开门的时候才亮，但足够照亮你真正在乎的那几样东西。',
    tags: ["理性", "独立", "战略家", "完美主义"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 1, 'W': 3},
    compat: defaultCompats['雪影娃娃'],
    shinyRate: 0.14,
  },
  奇丽花: {
    name: '奇丽花',
    type: '花语型',
    mbti: 'INFP',
    emoji: '🌸',
    el: '草',
    img: 'https://patchwiki.biligame.com/images/rocom/9/97/hll8utg7tvr4mgggxcjcr1b1u35iutz.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/8/8c/dbgfehb9vsrkwnn1jkxtibxciapkdur.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/9/97/hll8utg7tvr4mgggxcjcr1b1u35iutz.png',
    intro: '我不说话的时候，才是我最吵的时候。',
    desc: '你不需要说话，光是站在那里就是一道风景。\n\n别人急着表达自己，你只是安静地开花。但你知道——最持久的影响力，从来都不是喊出来的，是开出来的。你的存在本身就是一种回答。',
    tags: ["安静", "美丽", "神秘", "自然"],
    expect: {'E': 1, 'S': 1, 'B': 1, 'M': 2, 'W': 3},
    compat: defaultCompats['奇丽花'],
    shinyRate: 0.1,
  },
  小皮球: {
    name: '小皮球',
    type: '弹弹型',
    mbti: 'ESFP',
    emoji: '🔵',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/2/23/bmkkjpeacnqrk7aq7huu369aa5zr6fj.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/1/11/coplggyd0xwtvzzkw5d1say369yg1oy.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/2/23/bmkkjpeacnqrk7aq7huu369aa5zr6fj.png',
    intro: '我滚到哪里，快乐就跟到哪里。',
    desc: '你不需要目的地，滚动的过程本身就是意义。\n\n别人问你「你要去哪」，你说「不知道，但我很开心」。这种「无目的的快乐」在成年人眼里是不成熟，在你眼里是天赋。你被弹开一百次，第一百零一次照样弹回来。',
    tags: ["活泼", "可爱", "乐天", "弹性"],
    expect: {'E': 3, 'S': 1, 'B': 2, 'M': 1, 'W': 2},
    compat: defaultCompats['小皮球'],
    shinyRate: 0.12,
  },
  月牙雪熊: {
    name: '月牙雪熊',
    type: '雪熊型',
    mbti: 'ISTJ',
    emoji: '🐻‍❄️',
    el: '冰',
    img: 'https://patchwiki.biligame.com/images/rocom/2/25/2pmvd14ewtepuer9r87g9t7lbfd2v31.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/5/5d/0cskl2u4wneivk2icntkrcaiwuwv4yq.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/2/25/2pmvd14ewtepuer9r87g9t7lbfd2v31.png',
    intro: '冬天不是我的敌人，是我的被子。',
    desc: '你走路很慢，但每一步都踩得很实。\n\n别人急着赶路，你在雪地里留下一串整齐的脚印。你不怕冷，因为你的身体里有一座永远不会熄灭的壁炉——只是外人看不到。',
    tags: ["沉稳", "冬眠", "白色", "耐寒"],
    expect: {'E': 1, 'S': 2, 'B': 2, 'M': 1, 'W': 1},
    compat: defaultCompats['月牙雪熊'],
    shinyRate: 0.08,
  },
  格兰球: {
    name: '格兰球',
    type: '滚动型',
    mbti: 'ESFJ',
    emoji: '🎱',
    el: '石',
    img: 'https://patchwiki.biligame.com/images/rocom/4/4e/cav3gun98ax62yrpx33a524az878hq8.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/6/6c/ti7vsccgrnfmugk27891cc9726d15j5.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/4/4e/cav3gun98ax62yrpx33a524az878hq8.png',
    intro: '滚得快不重要，滚得开心才重要。',
    desc: '你是人群里的润滑剂，冲突到你这里就自动滑过去了。\n\n别人争得头破血流，你只是滚过去，把两边的棱角都磨平。你的圆滑不是虚伪，是你真的不想看到任何人受伤。',
    tags: ["滚动", "社交", "快乐", "圆滑"],
    expect: {'E': 2, 'S': 3, 'B': 2, 'M': 1, 'W': 1},
    compat: defaultCompats['格兰球'],
    shinyRate: 0.11,
  },
  獠牙猪: {
    name: '獠牙猪',
    type: '冲锋型',
    mbti: 'ESTP',
    emoji: '🐗',
    el: '普通',
    img: 'https://patchwiki.biligame.com/images/rocom/4/4f/tu0dhncbrnstzl3ugzzovrfq8ckfx6q.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/e/e7/9k7bizwcoun5u7cvgvqgchfd9dmyxou.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/4/4f/tu0dhncbrnstzl3ugzzovrfq8ckfx6q.png',
    intro: '我的獠牙不是为了吓人，是为了开路。',
    desc: '前面有墙？撞开。前面有河？蹚过去。\n\n你不是没脑子，你只是觉得想太多浪费时间。你的冲锋替团队省掉了无数个「再讨论一下」的会议。当然，你也撞坏过不少不该撞的东西——但那又怎样，至少你动了。',
    tags: ["冲锋", "勇猛", "野猪", "无畏"],
    expect: {'E': 3, 'S': 1, 'B': 3, 'M': 2, 'W': 1},
    compat: defaultCompats['獠牙猪'],
    shinyRate: 0.06,
  },
  落陨星兔: {
    name: '落陨星兔',
    type: '陨星型',
    mbti: 'INFJ',
    emoji: '🌠',
    el: '光',
    img: 'https://patchwiki.biligame.com/images/rocom/d/d0/nmyyzhqjwzlpk57arau048cc5amx1ly.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/8/86/jeo10wvmxho14u7cdmib8272dqfuzpr.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/d/d0/nmyyzhqjwzlpk57arau048cc5amx1ly.png',
    intro: '我是一颗选择坠落的星星，只为照亮你。',
    desc: '你明明可以留在天上，却选择坠落到人间。\n\n别人笑你傻，说高处多好。但你只是想离你想照亮的人近一点。坠落的过程很痛，但你不在乎——你本来就不是为了舒服才来的。',
    tags: ["星空", "坠落", "兔子", "光芒"],
    expect: {'E': 1, 'S': 3, 'B': 1, 'M': 2, 'W': 1},
    compat: defaultCompats['落陨星兔'],
    shinyRate: 0.09,
  },
  贝古斯: {
    name: '贝古斯',
    type: '古械型',
    mbti: 'INTJ',
    emoji: '🏛️',
    el: '机械',
    img: 'https://patchwiki.biligame.com/images/rocom/4/4b/bb16l3qu9p7d7is535keku5y4ucg2gf.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/0/0d/8cvnsom0kdicxcvjnut1lewivnuxgr2.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/4/4b/bb16l3qu9p7d7is535keku5y4ucg2gf.png',
    intro: '齿轮转动了三千年，只为等一个懂我的人。',
    desc: '你不是过时，你是太超前了。\n\n别人的脑子装的是 App，你的脑子里装的是操作系统。你说话很慢，因为每个词都经过了三层加密。等你终于开口的时候，话题已经换三轮了——所以你选择不说。',
    tags: ["古代", "机械", "沉默", "永恒"],
    expect: {'E': 2, 'S': 1, 'B': 3, 'M': 1, 'W': 2},
    compat: defaultCompats['贝古斯'],
    shinyRate: 0.05,
  },
  雅丹鬃: {
    name: '雅丹鬃',
    type: '风鬃型',
    mbti: 'ENFP',
    emoji: '🌬️',
    el: '翼',
    img: 'https://patchwiki.biligame.com/images/rocom/0/09/qmptqwmkwk515cwfqit1nzvkkxg425r.png',
    normalImg: 'https://patchwiki.biligame.com/images/rocom/c/c2/1qy2ib6i9lr8p6c9gh8mfuo0df9a1tb.png',
    shinyImg: 'https://patchwiki.biligame.com/images/rocom/0/09/qmptqwmkwk515cwfqit1nzvkkxg425r.png',
    intro: '风从我的鬃毛间穿过，带走了所有的秘密。',
    desc: '你路过的地方，连空气都变得不一样了。\n\n不是你在追风，是风在追你。你不需要扎根，因为你本身就是流动的。别人问你「你的家在哪」，你说「下一个风向」。',
    tags: ["风", "自由", "鬃毛", "轻盈"],
    expect: {'E': 3, 'S': 2, 'B': 1, 'M': 1, 'W': 1},
    compat: defaultCompats['雅丹鬃'],
    shinyRate: 0.07,
  },
};

export const fallbackResult: PetResult = {
  name: '果冻',
  deepDesc: '在洛克王国的数据库里，果冻是唯一一个所有维度同时出现在最高和最低区间的精灵。系统试图给你贴标签时，CPU 直接过热——因为你就是行走的逻辑错误。\n\n你不被定义，无法归类。不是因为你太特殊，而是因为你把本该互斥的特质，全部塞进了同一个灵魂里。你不是规则的例外，你是规则本身都没考虑过的情况。',
  type: '混沌型', mbti: '????', emoji: '🍮', el: '水', img: '/jelly.png',
  intro: '系统扫描了你三遍，每次返回的结果都不一样。',
  desc: '你安静得像影子，独来独往从不主动发声——但你的战斗风格像火山爆发，情绪一起来连自己都害怕。\n\n这种矛盾的配方让标准图鉴彻底死机：低能量+独行侠+正面硬刚+情绪爆炸+现世安稳——你同时是隐士和狂战士，是禅者和暴徒。没有任何标签能框住你，因为你自己就是一个不断自相矛盾的存在。\n\n果冻不是「没有形状」，它是「同时具有所有形状」。你也是这样。',
  tags: ['混沌', '布丁进化', '特殊', '彩蛋'],
  expect: { E: 1, S: 1, B: 3, M: 3, W: 1 },
  compat: [{ name: '利灯鱼', type: '孤灯型' }, { name: '夜枭', type: '夜行型' }, { name: '雪影娃娃', type: '霜华型' }],
};

export const petKeys = Object.keys(results);
export const shinyKeys = Object.keys(shinyPets);

export const questions: Question[] = [
  {
    id: 'q1',
    text: '上线洛克王国，你更倾向于怎么安排？',
    options: [
      { label: '直奔竞技场 PK！', scores: { E: 3, S: 3, B: 2, M: 3, W: 1 } },
      { label: '回到家园研究孵蛋配方', scores: { E: 1, S: 1, B: 2, M: 1, W: 2 } },
      { label: '去野外探险，随缘大地图锄地', scores: { E: 3, S: 2, B: 2, M: 2, W: 3 } },
      { label: '在家整理精灵仓库，优化队伍配置', scores: { E: 2, S: 1, B: 1, M: 2, W: 1 } },
    ],
  },
  {
    id: 'q2',
    text: '游戏推送：「限定精灵开启 72 小时获取活动」，你的反应？',
    options: [
      { label: '立刻清空日程，三天爆肝必拿下', scores: { E: 3, S: 1, B: 3, M: 3, W: 1 } },
      { label: '先研究获取机制，算清性价比再决定要不要肝', scores: { E: 1, S: 1, B: 1, M: 1, W: 3 } },
      { label: '拉几个朋友一起冲，组队效率翻倍', scores: { E: 2, S: 3, B: 2, M: 2, W: 2 } },
      { label: '错过就错过，不打算被活动倒计时绑架', scores: { E: 1, S: 1, B: 1, M: 2, W: 2 } },
    ],
  },
  {
    id: 'q3',
    text: '游戏里一个很久没冒泡的老朋友突然找你：「我刚回归，版本完全跟不上了……」你的反应是？',
    options: [
      { label: '立刻拉他组队，带他捉一圈新的精灵', scores: { E: 2, S: 3, B: 3, M: 2, W: 2 } },
      { label: '私聊把自己整理的版本攻略和配队思路一并发过去', scores: { E: 1, S: 2, B: 1, M: 1, W: 3 } },
      { label: '「来我家园看看，我新孵了好多精灵蛋送给你」', scores: { E: 2, S: 3, B: 1, M: 3, W: 2 } },
      { label: '「慢慢追，版本不催」（继续刷自己的）', scores: { E: 1, S: 1, B: 1, M: 1, W: 1 } },
    ],
  },
  {
    id: 'q4',
    text: '捉满了好几个背包，每次出的都不是最优性格，你的心态是？',
    options: [
      { label: '继续死磕！我就不信这个邪，今晚不睡也要出货！', scores: { E: 3, S: 1, B: 3, M: 3, W: 1 } },
      { label: '查攻略，看看有没有下位替代', scores: { E: 1, S: 1, B: 2, M: 1, W: 2 } },
      { label: '先放放，等运气好的时候再说，强扭的瓜不甜', scores: { E: 2, S: 2, B: 1, M: 2, W: 3 } },
      { label: '算了，什么性格也能用，玩游戏开心最重要', scores: { E: 2, S: 2, B: 1, M: 3, W: 3 } },
    ],
  },
  {
    id: 'q5',
    text: '巅峰对决新赛季开启了，作为训练师，你的备赛节奏是？',
    options: [
      { label: '提前一周研究当前 meta，整理两套阵容备用', scores: { E: 1, S: 1, B: 1, M: 1, W: 3 } },
      { label: '直接上号开打，边打边调，相信临场反应', scores: { E: 3, S: 2, B: 3, M: 3, W: 1 } },
      { label: '喊几个老搭档陪练，磨好默契再上天梯', scores: { E: 2, S: 3, B: 2, M: 2, W: 2 } },
      { label: '不打巅峰，蹲在观战频道看大佬对决就够了', scores: { E: 1, S: 1, B: 1, M: 1, W: 2 } },
    ],
  },
  {
    id: 'q6',
    text: '如果你的精灵会说话，你觉得它最可能对你说什么？',
    options: [
      { label: '「主人，今天又陪我训练这么久，辛苦你啦」', scores: { E: 1, S: 2, B: 2, M: 3, W: 2 } },
      { label: '「带我去看看王国外面的世界吧，我想看更多风景」', scores: { E: 2, S: 2, B: 2, M: 2, W: 3 } },
      { label: '「下次对战让我冲在前面，我会保护好你的」', scores: { E: 3, S: 2, B: 3, M: 3, W: 2 } },
      { label: '「我喜欢这样安安静静的下午——只有你和我」', scores: { E: 1, S: 1, B: 1, M: 2, W: 1 } },
    ],
  },
  {
    id: 'q7',
    text: '精灵图鉴还差最后几只就能点亮全图鉴，但都是低概率刷新或难捕的精灵。你的搜集策略是？',
    options: [
      { label: '「不眠不休，今晚就要把图鉴点亮」', scores: { E: 3, S: 1, B: 3, M: 3, W: 1 } },
      { label: '分阶段攻略，按每只的最佳出货地图逐个排期', scores: { E: 1, S: 1, B: 1, M: 1, W: 3 } },
      { label: '拉几个朋友帮我开车，速通完事', scores: { E: 2, S: 3, B: 2, M: 2, W: 2 } },
      { label: '图鉴慢慢来，能凑齐就凑齐，不强求', scores: { E: 1, S: 1, B: 1, M: 2, W: 2 } },
    ],
  },
  {
    id: 'q8',
    text: '你刷到一个攻略帖说：「特定地图特定时段反复刷新，异色精灵概率会变高。」你？',
    options: [
      { label: '「立刻就去刷！今晚必出货」', scores: { E: 3, S: 1, B: 3, M: 3, W: 1 } },
      { label: '先做对比实验，统计样本验证一下真假', scores: { E: 1, S: 1, B: 1, M: 1, W: 3 } },
      { label: '拉一群朋友轮流帮忙刷，凑出大样本', scores: { E: 2, S: 3, B: 2, M: 2, W: 2 } },
      { label: '「异色看缘分，刷不出就算了」', scores: { E: 1, S: 1, B: 1, M: 1, W: 2 } },
    ],
  },
  {
    id: 'q9',
    text: '你的家园终于布置好了，但关于布置风格，你的主要方式是？',
    options: [
      { label: '从网上照搬别人的设计，省事又好看', scores: { E: 2, S: 2, B: 1, M: 1, W: 2 } },
      { label: '按自己的风格精心布置，每个角落都有讲究', scores: { E: 1, S: 1, B: 1, M: 3, W: 3 } },
      { label: '随意摆放就行，看着舒服就够了', scores: { E: 1, S: 1, B: 1, M: 1, W: 1 } },
      { label: '只要能生蛋（孵蛋），怎么摆都可以', scores: { E: 2, S: 1, B: 3, M: 2, W: 1 } },
    ],
  },
  {
    id: 'q10',
    text: '如果可以在王国里过一种理想生活，你希望是？',
    options: [
      { label: '在自己的花园里种满各种精灵，每天晒晒太阳', scores: { E: 1, S: 2, B: 1, M: 1, W: 3 } },
      { label: '成为王国最强的训练师，让所有人都知道我的名字', scores: { E: 3, S: 3, B: 3, M: 3, W: 2 } },
      { label: '和三五好友拉拉手，探索未知的地图', scores: { E: 3, S: 3, B: 2, M: 3, W: 3 } },
      { label: '我要记录所有精灵的属性和技能', scores: { E: 1, S: 1, B: 2, M: 1, W: 3 } },
    ],
  },
  {
    id: 'q11',
    text: '你的战斗风格素？',
    options: [
      { label: '硬刚！什么技能数字大用什么！', scores: { E: 3, S: 2, B: 3, M: 3, W: 1 } },
      { label: '冷静分析，找出克制这个技能的办法', scores: { E: 1, S: 1, B: 2, M: 1, W: 3 } },
      { label: '口臭攻击！', scores: { E: 3, S: 3, B: 2, M: 3, W: 2 } },
      { label: '默默记下，下次先ban这个技能', scores: { E: 2, S: 1, B: 1, M: 1, W: 2 } },
    ],
  },
  {
    id: 'q12',
    text: '如果只能带一只精灵去未知的远方冒险，你会选？',
    options: [
      { label: '火系或电系精灵，炽热的斗志从不熄灭', scores: { E: 3, S: 2, B: 3, M: 2, W: 2 } },
      { label: '水系或冰系精灵，温柔与冷静并存', scores: { E: 1, S: 2, B: 1, M: 2, W: 3 } },
      { label: '草系或妖精系精灵，自然是最好的伙伴', scores: { E: 2, S: 2, B: 2, M: 2, W: 3 } },
      { label: '幽灵、恶魔或龙系精灵，神秘力量令人敬畏', scores: { E: 1, S: 1, B: 2, M: 1, W: 3 } },
      { label: '石系、机械或普通系精灵，坚实可靠从不掉链子', scores: { E: 2, S: 2, B: 2, M: 2, W: 2 } },
    ],
  },
];

export const dimExplanations: Record<string, Record<string, string>> = {
  E: {
    H: '电力过剩是你的常态。把你关在安静的房间里，等于把火锅的火关掉——你会凝固、会焦躁、会开始拆家。人群是你的充电桩，喧闹是你的白噪音。别人休息的方式是躺平，你休息的方式是换个场子继续嗨。',
    L: '社交对你来说是耗电项，独处才是回血的唯一方式。你不需要通过「被看见」来确认自己的存在，你的存在感是内置的、自洽的。外面越吵，你反而越能静下来——因为你知道那跟你没关系。',
    M: '你可以连续嗨三天，也可以突然消失半个月。没人能预测你什么时候想社交、什么时候想关机，包括你自己。这种不可预测性让你很难被定义，但也让你活得特别自由。',
  },
  S: {
    H: '你微信列表里的「最近联系」永远不会少于二十个人。独处超过三小时，你就会开始怀疑人生。你的友谊是广谱型的——从凌晨三点陪你哭到中午十二点请你吃饭，你全都要。数量对你来说不是负担，是资产。',
    L: '你的朋友圈小到可以用一只手数完，但每一个都是可以托付后背的人。你不害怕孤独，你害怕的是「为了不被孤独而硬凑的热闹」。与其在人群里当背景板，不如在自己的房间里当主角。',
    M: '有人找你你就去，没人找你就自己玩。你永远不会因为「没朋友」而焦虑，也永远不会因为「想一个人」而愧疚。这种「来则欢迎，去则不留」的社交态度，是成年人世界里最稀缺的奢侈。',
  },
  B: {
    H: '你大脑里的「犹豫」按钮被抠掉了。看到机会第一反应是冲，看到敌人第一反应是干。复盘？那是赢之后才需要考虑的事。你的字典里没有「准备一下」，只有「就是现在」。这种本能替你抢到了很多别人还在犹豫的机会。',
    L: '你出手之前，大脑已经跑完了三遍模拟器。别人看到的是你在「犹豫」，你看的是自己在「排雷」。这种谨慎让你错过过一些风口，但也让你避开了更多的坑。你的胜率不是来自天赋，是来自耐心。',
    M: '你有一套自己的「战斗开关」。遇到值得的对手，你比谁都莽；遇到不配的场面，你比谁都佛。这种「看碟下菜」的能力，让你既能享受冲锋的快感，又能保住不被收割的底线。',
  },
  M: {
    H: '你的情绪没有静音模式。开心的时候恨不得昭告天下，难过的时候连路过的狗都想倾诉。有人说你戏多，但你只是拒绝把感受压缩成表情包。活得浓烈是你的选择，你要的是真实，不是体面。',
    L: '你的情绪管理系统是内建的，不需要外部补丁。别人失恋了要发十条朋友圈，你只是默默把头像从彩色换成黑白，三天后又换回来了。不是你没有感受，是你的感受被关在一个隔音很好的房间里——你自己听得到，外面的人只能猜。',
    M: '你允许自己难过，但不允许自己沉溺。你会哭，但会定闹钟；你会生气，但会记笔记。这种「有管理的失控」让你看起来总是很稳，其实你只是比别人更早学会了——情绪是信号，不是指令。',
  },
  W: {
    H: '你是不可能被同一个笼子关两次的鸟。眼前的安稳再舒服，也挡不住你往远处看的眼睛。未知对你来说是磁铁， routine 对你来说是毒药。你也不知道终点在哪，但你确信——不在此刻站着的这个地方。',
    L: '你把「过好今天」当成一种信仰。远处的风景你当然也看，但你更相信——脚下的这一步如果走歪了，远方再美也到不了。你的世界观不宏大，但很坚固，像老房子里的承重墙，不起眼，但没它不行。',
    M: '你有一颗不安分的心，和一双踏实的脚。这听起来很矛盾，但你处理得很好——想飞的欲望负责给你方向，走路的耐心负责把你送到。你既不是空想家，也不是井底蛙，你是那种「一边造翅膀一边学走路」的人。',
  },
};
